blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/mohameodo/agentai/discussions
    about: General discussions, ideas, and community support
  - name: 📚 Documentation
    url: https://github.com/mohameodo/agentai/tree/main/docs
    about: Check out the documentation for setup and usage guides
  - name: 🚀 Live Demo
    url: https://ai.nexiloop.com
    about: See the application in action
